name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-dir: [ 'json-server' ]
    defaults:
      run:
        working-directory: ${{ matrix.build-dir }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Authenticate against registry
        run: |
          echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      - name: debug
        run: |
          echo ${{ github.repository }}
          echo ${{ github.repository }}/${{ matrix.build-dir }}
      - name: Build and push image
        run: |
          IMAGE_ID=${{ github.repository }}/${{ matrix.build-dir }}
          IMAGE_TAG=$(echo ${{ github.sha }} | cut -c1-7)
          docker build --tag $IMAGE_ID:$IMAGE_TAG --tag $IMAGE_ID:latest .
          docker push $IMAGE_ID:$IMAGE_TAG
          docker push $IMAGE_ID:latest
