name: Build
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-dir: [ 'json-server', 'json-server-node' ]
    defaults:
      run:
        working-directory: ${{ matrix.build-dir }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build docker image (${{ matrix.build-dir }})
        run: docker build .
